Numpy is a Linear Algebra Library for Python. The reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries.

# NumPy Arrays

In [2]:
import numpy as np

In [3]:
my_list = [1,2,3]

In [4]:
my_list

[1, 2, 3]

In [5]:
np.array(my_list)

array([1, 2, 3])

In [6]:
# We can assign the arrays we create as such
arr = np.array(my_list)

In [7]:
arr

array([1, 2, 3])

In [8]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]

In [9]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Do NOT confuse linspace() with arange()

arange() gives you the list of numbers in an incremet you specify with the 3rd parameter

linspace() divides the range you give with the 1st and the 2nd parameters into the number of pieces given with the 3rd param

In [21]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [22]:
np.linspace(0,10,40)

array([ 0.        ,  0.25641026,  0.51282051,  0.76923077,  1.02564103,
        1.28205128,  1.53846154,  1.79487179,  2.05128205,  2.30769231,
        2.56410256,  2.82051282,  3.07692308,  3.33333333,  3.58974359,
        3.84615385,  4.1025641 ,  4.35897436,  4.61538462,  4.87179487,
        5.12820513,  5.38461538,  5.64102564,  5.8974359 ,  6.15384615,
        6.41025641,  6.66666667,  6.92307692,  7.17948718,  7.43589744,
        7.69230769,  7.94871795,  8.20512821,  8.46153846,  8.71794872,
        8.97435897,  9.23076923,  9.48717949,  9.74358974, 10.        ])

To create Identity Matrices

In [23]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Random() methods

In [24]:
np.random.rand(5)

array([0.82638458, 0.117495  , 0.50153933, 0.73203557, 0.20840891])

In [25]:
np.random.rand(3,4)

array([[0.27146829, 0.9375353 , 0.18620909, 0.40412661],
       [0.04906887, 0.51146834, 0.64094821, 0.76330791],
       [0.87192565, 0.77548491, 0.69542473, 0.56955859]])

In [29]:
np.random.randn(5)

array([ 0.28242577, -0.22973839, -1.73993967,  1.03214082,  0.45850763])

In [30]:
np.random.randint(1,100)

31

In [31]:
np.random.randint(1,100, 10)

array([44, 25, 12, 40, 52, 63, 64, 61, 43, 21])

In [32]:
arr = np.arange(25)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
ranarr = np.random.randint(0,50,10)

In [35]:
ranarr

array([11, 43, 16, 14, 18, 49, 23, 16, 14, 43])

In [37]:
# Note that when using reshape(m,n) method, the value of m*n must be equal to the size of the array we want to reshape.
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
ranarr

array([11, 43, 16, 14, 18, 49, 23, 16, 14, 43])

In [39]:
ranarr.max()

49

In [40]:
ranarr.min()

11

In [41]:
# To find out the LOCATIONS of the min and max values in an array, we can use argmax() and argmin() methods.
ranarr

array([11, 43, 16, 14, 18, 49, 23, 16, 14, 43])

In [42]:
ranarr.argmax()

5

In [58]:
ranarr.argmin()

0

In [59]:
arr = np.arange(3,31,3)

In [60]:
arr

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [61]:
arr = arr.reshape(5,2)

In [62]:
arr.shape

(5, 2)

In [63]:
arr.dtype

dtype('int32')

One thing to note: if we don't want to use the methods explicity by going over np.stuff.stuff every time, we can do the following

In [64]:
from numpy.random import randint as ri

In [65]:
ri(2,10)

4

# NumPy Indexing and Selection

In [66]:
import numpy as np

In [67]:
arr = np.arange(0,11)

In [68]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
arr[8]

8

In [70]:
arr[1:5]

array([1, 2, 3, 4])

In [73]:
# Broadcasting a value over an array.
arr = np.arange(0,17)

In [74]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [76]:
arr[0:5] = 100

In [77]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16])

In [78]:
# Slicing an array.
arr = np.arange(0,11)

In [87]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
slice_arr = arr[2:7]

In [89]:
slice_arr

array([2, 3, 4, 5, 6])

In [90]:
slice_arr[:] = 99

In [91]:
slice_arr

array([99, 99, 99, 99, 99])

In [92]:
arr

array([ 0,  1, 99, 99, 99, 99, 99,  7,  8,  9, 10])

In [93]:
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
# This is really important.
# Note that we sliced the elements from 2 up to the element 7 from the array arr and named it slice_arr
# And then we changed the elements of slice_arr and assigned all of them to 99
# But note that it is not only the elements of slice_arr that have been changed
# The elements of arr, more specifically, from the index 2 up to the index 7 have been changed too!
# Its because we didn't copy the data from arr into the slice_arr
# It is just a way to view it, therefore when we change the data in slice_arr, the data it's being represented of 
# changes too.

In [94]:
# When we want to COPY and array and make changes on it WITHOUT affecting the original array, we can use the copy() method.
arr_copy = arr.copy()

In [95]:
arr_copy

array([ 0,  1, 99, 99, 99, 99, 99,  7,  8,  9, 10])

In [96]:
arr

array([ 0,  1, 99, 99, 99, 99, 99,  7,  8,  9, 10])

In [97]:
arr_copy[2:7] = 1000

In [98]:
arr_copy

array([   0,    1, 1000, 1000, 1000, 1000, 1000,    7,    8,    9,   10])

In [99]:
arr

array([ 0,  1, 99, 99, 99, 99, 99,  7,  8,  9, 10])

In [100]:
# As can be seen above, the array arr didn't change, that's what we wanted.

# Indexing a 2D array

In [101]:
import numpy as np

In [102]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [103]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
# Accessing the elements of a 2D array using double square brackets notation.

In [104]:
arr_2d[2][2]

45

In [105]:
arr_2d[1][2]

30

In [106]:
# Accessing the elements of a 2D array using single square bracket AND comma notation.

In [107]:
arr_2d[2,2]

45

In [109]:
arr_2d[1,2]

30

In [110]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [111]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

# Conditional Selections

In [112]:
arr = np.arange(1,11)

In [113]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [117]:
bool_arr = arr > 5

In [118]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [121]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [122]:
# The more common syntax notation we are gonna use is:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [123]:
arr[arr < 3]

array([1, 2])

# NumPy Operations

* Array with Array
* Array with Scalars
* Universal Array Functions

In [124]:
import numpy as np

In [125]:
arr = np.arange(0,11)

In [126]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [127]:
arr = arr + 1

In [128]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [129]:
arr = arr * 3

In [130]:
arr

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33])